name: 🛠️ Request New Feature
description: Let us know what you would like to see added.
labels: [feature]
body:
  - type: textarea
    attributes:
      label: New feature motivation
      description: Describe the context, the use-case and the advantages of the feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: New feature description
      description: Describe the functional changes that would have to be made.
    validations:
      required: true

  - type: textarea
    attributes:
      label: New feature implementation
      description: Optionally describe the technical changes to be made.
    validations:
      required: false
